export { default as Home } from './Home/Home'
export { default as Playlist } from './Playlist/Playlist'
export { default as Artist } from './Artist/Artist'
export { default as Authentication } from './Authentication/Authentication'
export { default as MyPlaylist } from './MyPlaylist/MyPlaylist'
export { default as MySong } from './MySong/MySong'
export { default as Search } from './Search/Search'
export { default as Category } from './Category/Category'
